# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import leilao_pb2 as leilao__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in leilao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SistemaLeilaoStub(object):
    """Serviço Principal (Gateway e Microsserviços internos)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarLeilao = channel.unary_unary(
                '/leilao.SistemaLeilao/CriarLeilao',
                request_serializer=leilao__pb2.DadosLeilao.SerializeToString,
                response_deserializer=leilao__pb2.RespostaID.FromString,
                _registered_method=True)
        self.ListarLeiloes = channel.unary_unary(
                '/leilao.SistemaLeilao/ListarLeiloes',
                request_serializer=leilao__pb2.Vazio.SerializeToString,
                response_deserializer=leilao__pb2.ListaLeiloes.FromString,
                _registered_method=True)
        self.DarLance = channel.unary_unary(
                '/leilao.SistemaLeilao/DarLance',
                request_serializer=leilao__pb2.Lance.SerializeToString,
                response_deserializer=leilao__pb2.RespostaStatus.FromString,
                _registered_method=True)
        self.AcompanharLeiloes = channel.unary_stream(
                '/leilao.SistemaLeilao/AcompanharLeiloes',
                request_serializer=leilao__pb2.Identificacao.SerializeToString,
                response_deserializer=leilao__pb2.Evento.FromString,
                _registered_method=True)


class SistemaLeilaoServicer(object):
    """Serviço Principal (Gateway e Microsserviços internos)
    """

    def CriarLeilao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarLeiloes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DarLance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcompanharLeiloes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SistemaLeilaoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarLeilao': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarLeilao,
                    request_deserializer=leilao__pb2.DadosLeilao.FromString,
                    response_serializer=leilao__pb2.RespostaID.SerializeToString,
            ),
            'ListarLeiloes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarLeiloes,
                    request_deserializer=leilao__pb2.Vazio.FromString,
                    response_serializer=leilao__pb2.ListaLeiloes.SerializeToString,
            ),
            'DarLance': grpc.unary_unary_rpc_method_handler(
                    servicer.DarLance,
                    request_deserializer=leilao__pb2.Lance.FromString,
                    response_serializer=leilao__pb2.RespostaStatus.SerializeToString,
            ),
            'AcompanharLeiloes': grpc.unary_stream_rpc_method_handler(
                    servicer.AcompanharLeiloes,
                    request_deserializer=leilao__pb2.Identificacao.FromString,
                    response_serializer=leilao__pb2.Evento.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'leilao.SistemaLeilao', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('leilao.SistemaLeilao', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SistemaLeilao(object):
    """Serviço Principal (Gateway e Microsserviços internos)
    """

    @staticmethod
    def CriarLeilao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leilao.SistemaLeilao/CriarLeilao',
            leilao__pb2.DadosLeilao.SerializeToString,
            leilao__pb2.RespostaID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarLeiloes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leilao.SistemaLeilao/ListarLeiloes',
            leilao__pb2.Vazio.SerializeToString,
            leilao__pb2.ListaLeiloes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DarLance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leilao.SistemaLeilao/DarLance',
            leilao__pb2.Lance.SerializeToString,
            leilao__pb2.RespostaStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcompanharLeiloes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/leilao.SistemaLeilao/AcompanharLeiloes',
            leilao__pb2.Identificacao.SerializeToString,
            leilao__pb2.Evento.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BancoExternoStub(object):
    """Serviço do "Banco" Externo
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SolicitarPagamento = channel.unary_unary(
                '/leilao.BancoExterno/SolicitarPagamento',
                request_serializer=leilao__pb2.DadosPagamento.SerializeToString,
                response_deserializer=leilao__pb2.LinkPagamento.FromString,
                _registered_method=True)


class BancoExternoServicer(object):
    """Serviço do "Banco" Externo
    """

    def SolicitarPagamento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BancoExternoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SolicitarPagamento': grpc.unary_unary_rpc_method_handler(
                    servicer.SolicitarPagamento,
                    request_deserializer=leilao__pb2.DadosPagamento.FromString,
                    response_serializer=leilao__pb2.LinkPagamento.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'leilao.BancoExterno', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('leilao.BancoExterno', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BancoExterno(object):
    """Serviço do "Banco" Externo
    """

    @staticmethod
    def SolicitarPagamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leilao.BancoExterno/SolicitarPagamento',
            leilao__pb2.DadosPagamento.SerializeToString,
            leilao__pb2.LinkPagamento.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NotificacaoPagamentoStub(object):
    """Serviço de Callback (Webhook) que o MS Pagamento vai expor
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceberStatus = channel.unary_unary(
                '/leilao.NotificacaoPagamento/ReceberStatus',
                request_serializer=leilao__pb2.ResultadoPagamento.SerializeToString,
                response_deserializer=leilao__pb2.Vazio.FromString,
                _registered_method=True)


class NotificacaoPagamentoServicer(object):
    """Serviço de Callback (Webhook) que o MS Pagamento vai expor
    """

    def ReceberStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificacaoPagamentoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceberStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceberStatus,
                    request_deserializer=leilao__pb2.ResultadoPagamento.FromString,
                    response_serializer=leilao__pb2.Vazio.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'leilao.NotificacaoPagamento', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('leilao.NotificacaoPagamento', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificacaoPagamento(object):
    """Serviço de Callback (Webhook) que o MS Pagamento vai expor
    """

    @staticmethod
    def ReceberStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leilao.NotificacaoPagamento/ReceberStatus',
            leilao__pb2.ResultadoPagamento.SerializeToString,
            leilao__pb2.Vazio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
